name: panel
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - pandas
  - panel
  - holoviews
  - hvplot
  - jupyterlab
  - pytest
  - appmode
  - pip
# pip
  - pip:
      - mortgage
      - jupyteranalytics
variables:
  - GOOGLE_ANALYTICS_TRACKING_ID: UA-142377027-1
# install @pyviz/jupyterlab_pyviz jupyter labextension afterwards as well if using jupyterlab
